#!/usr/bin/env python3
"""Rebuild the icon font from only the Tabler icons the site uses.

The full Tabler webfont is ~800KB for ~5,000 icons; the site uses about a
hundred. This scans index.html, js/ and css/ for `ti-<name>` classes and
writes a subset font plus the matching CSS:

    fonts/icons.woff2   css/icons.css

Run it after using an icon the site hasn't used before, or that icon
renders blank:

    python3 -m venv /tmp/iv && /tmp/iv/bin/pip install fonttools brotli
    /tmp/iv/bin/python scripts/build-icons.py
"""
import hashlib, pathlib, re, subprocess, sys, urllib.request

VERSION = "3.31.0"
BASE = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}/dist"
ROOT = pathlib.Path(__file__).resolve().parent.parent
# Names built by string concatenation, which a scan can't see.
EXTRA = {"arrows-minimize", "arrows-maximize"}

def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()

css = fetch(f"{BASE}/tabler-icons.min.css").decode()
glyphs = dict(re.findall(r'\.ti-([a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}', css))

used = set(EXTRA)
files = [ROOT / "index.html", *sorted((ROOT / "js").glob("*.js")), *sorted((ROOT / "css").glob("*.css"))]
for f in files:
    if f.name == "icons.css":
        continue
    used |= set(re.findall(r"\bti-([a-z0-9]+(?:-[a-z0-9]+)*)", f.read_text()))
names = sorted(n for n in used if n in glyphs)

tmp = ROOT / "fonts" / "_tabler-full.woff2"
tmp.write_bytes(fetch(f"{BASE}/fonts/tabler-icons.woff2"))
subprocess.run([sys.executable, "-m", "fontTools.subset", str(tmp),
                "--unicodes=" + ",".join("U+" + glyphs[n] for n in names),
                "--flavor=woff2", "--layout-features=", "--no-hinting",
                f"--output-file={ROOT / 'fonts' / 'icons.woff2'}"], check=True)
tmp.unlink()

# Versioned by content: the service worker serves same-origin files from
# cache first, so a rebuilt font needs a new URL to be picked up.
stamp = hashlib.sha1((ROOT / "fonts" / "icons.woff2").read_bytes()).hexdigest()[:8]
rules = "".join(f'.ti-{n}:before{{content:"\\{glyphs[n]}"}}' for n in names)
(ROOT / "css" / "icons.css").write_text(
    f"/* Tabler Icons {VERSION} (MIT), subset to the {len(names)} icons this site uses.\n"
    "   Generated by scripts/build-icons.py; don't edit by hand. */\n"
    '@font-face{font-family:"tabler-icons";font-style:normal;font-weight:400;font-display:block;'
    f'src:url("../fonts/icons.woff2?v={stamp}") format("woff2")}}'
    '.ti{font-family:"tabler-icons"!important;speak:none;font-style:normal;font-weight:normal;'
    "font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;"
    "-moz-osx-font-smoothing:grayscale}" + rules + "\n")
print(f"{len(names)} icons -> fonts/icons.woff2 ({(ROOT / 'fonts' / 'icons.woff2').stat().st_size // 1024}KB)")
